# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cec6c6155ab665df36f7e2efc7121fa3448db1df4843d9c3df94352096d2af9373e74c3f39c931d93a850f7572ba4edadef62db656455792f9fea09f90973ab

test:
  secret_key_base: cd7912687062552ae65e982851cc8ac2a8faf69c001fdad3a9e570d9bd4aad5e9c008516a438af68c1ab1762b8e22e9c71f3a0d10b947da8e0fbbd4bb5b252f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
